server:
  port: 8888
  context-path: /exam

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: admin

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379


mybatis:
  type-aliases-package: com.ysjt.exam.common.entity
  mapper-locations: classpath:mapper/*.xml




